# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # App services
    app.book.service:
        class: AppBundle\Service\BookService
        arguments: ['@doctrine.orm.entity_manager']

    app.author.service:
        class: AppBundle\Service\AuthorService
        arguments: ['@doctrine.orm.entity_manager']