# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # App services
    app.book.service:
        class: AppBundle\Service\BookService
        arguments: ['@doctrine.orm.entity_manager']

    app.author.service:
        class: AppBundle\Service\AuthorService
        arguments: ['@doctrine.orm.entity_manager']

    app.user.service:
        class: AppBundle\Service\UserService
        arguments: ['@doctrine.orm.entity_manager']

    app.user_book.service:
        class: AppBundle\Service\UserBookService
        arguments: ['@doctrine.orm.entity_manager']

    app.provider.oauth:
        class: AppBundle\Security\Core\User\OAuthUserProvider
        arguments: ['@doctrine.orm.entity_manager', '@security.encoder_factory']