<?php

namespace AdminBundle\Repository;

/**
 * UserBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserBookRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByUserAndBook($user, $book)
    {

    }
}
